# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy ASP.Net Core app to Azure Web App - BWSuDriveRestApi



# on:
#   push:
#     branches:
#       - deployment
#       - main
#   workflow_dispatch:

  
# jobs:  
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
                     
#       - name: Set up .NET Core
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: '7.x'
#           include-prerelease: true


#       - name: Build with dotnet
#         run: dotnet build --configuration Api



#       - name: dotnet publish
#         run: dotnet publish -c Api -o ${{env.DOTNET_ROOT}}/myapp

#       - name: App Settings Variable Substitution - Secrets
#         uses: microsoft/variable-substitution@v1
#         with:
#             files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
#         env:
#             ConnectionStrings.AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING }}
#             ApplicationSettings.JWT_Secret: ${{ secrets.BWSJWTPRODUCTIVSECRET }} 

#       - name: dotnet install ef
#         run: dotnet tool install -g dotnet-ef

#       - name: dotnet bundle migration
#         run: dotnet ef migrations bundle --runtime linux-x64 -p src/uDrive.Backend.Api/uDrive.Backend.Api.csproj -o ${{env.DOTNET_ROOT}}/myapp/migrate
    
#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v2
#         with:
#           name: .net-app
#           path: ${{env.DOTNET_ROOT}}/myapp

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v2
#         with:
#           name: .net-app

#       - name: Deploy to Azure Web App
#         id: deploy-to-webapp
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'BWSuDriveRestApi'
#           slot-name: 'Production'
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C81D7FA3EC14E84837262DFD0C50041 }}
#           package: .
